name: BuildAndTestAndRunKeycloak

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-dotnet@v1

    - uses: barimale/keycloak_with_linux_docker_action@master

    - name: UT Run Tests 
      run: dotnet test .\\UT.Keycloak.NET.Client.FluentAPI\\UT.Keycloak.NET.Client.FluentAPI.csproj --configuration Release