name: PushAndPack

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-dotnet@v1

    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget Add source 
      run: nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/barimale/index.json" -UserName barimale -Password ${{ secrets.GITHUB_TOKEN }}
      
    - name: Nuget Restore 
      run: nuget restore .\Keycloak.NET.Client.FluentAPI\Keycloak.NET.Client.FluentAPI.sln

    - name: Build Solution for Standard 2.1
      run: dotnet build .\Keycloak.NET.Client.FluentAPI\Keycloak.NET.Client.FluentAPI.sln --configuration Release

    - name: Build Solution for Net47
      run: dotnet build .\Keycloak.NET.Client.FluentAPI\Keycloak.NET.Client.FluentAPI.sln --configuration Release --framework net47 --output .\Keycloak.NET.Client.FluentAPI\Keycloak.NET.Client.FluentAPI\bin\Release\net47\  --force

    - name: Nuget Pack
      run: nuget pack .\Keycloak.NET.Client.FluentAPI\pack.nuspec -Properties Configuration=Release -OutputDirectory .\nugetPackages
      
    - name: Nuget Push
      run: nuget push .\nugetPackages\*.nupkg -Source GitHub 